FROM python:alpine

LABEL manteiner='ArthurBitt'

EXPOSE 5000

WORKDIR /server

COPY ./src/app.py /server/

RUN pip install flask && \
    pip install redis && \
    apk add curl

HEALTHCHECK  CMD \
    curl -sf localhost:5000/health || exit 1

CMD ["flask", "run", "--host", "0.0.0.0"]

